# Generated by Django 5.1.3 on 2024-12-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uplode/'),
        ),
    ]
