# Generated by Django 5.1.3 on 2024-12-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV (Sport Utility Vehicle)'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Sports Car', 'Sports Car'), ('EV', 'Electric Vehicle (EV)')], max_length=100, null=True),
        ),
    ]
